---
title: "R Notebook"
output: html_notebook
---

```{r, include=FALSE}
library(Seurat)
library(SingleCellExperiment)
library(SingleR)
library(SeuratDisk)
library(celldex)
library(tidyverse)
```

```{r, include=FALSE}
adata_seurat <- LoadH5Seurat("lympnode.h5seurat")
```
```{r}
ref_cells <- celldex::DatabaseImmuneCellExpressionData()
```


```{r}
sce <- as.SingleCellExperiment(adata_seurat)
sce
```
```{r}
res_anno <- SingleR(test = sce, ref = ref_cells, labels = ref_cells$label.main)
```

```{r}
table(res_anno$labels)
```

```{r}
# write.csv(data.frame(anno = res_anno$labels), "lymp_node_annotation.csv")
```
```{r}
adata_seurat$label <- factor(res_anno$labels)
adata_seurat
```

```{r}
adata_seurat <- FindNeighbors(adata_seurat,reduction = "pca", dims = 1:50, k.param = 4)
adata_seurat <- FindClusters(adata_seurat, resolution = 0.5)
adata_seurat <- RunUMAP(adata_seurat, dims = 1:50)

```
```{r}
Idents(adata_seurat) <- adata_seurat$clusters
DimPlot(adata_seurat, reduction = "umap", label = TRUE)
```
```{r}
Idents(adata_seurat) <- adata_seurat$label
DimPlot(adata_seurat, reduction = "umap")
```

```{r}
adata_seurat@meta.data$total_counts
```

```{r}
test_spatial_seurat <- Load10X_Spatial("D:\\Studies and Research\\Spatial scRNAseq\\data\\V1_Human_Lymph_Node")
```
```{r}
test_spatial_seurat@meta.data
```
```{r}
SpatialFeaturePlot(test_spatial_seurat, features = "nFeature_Spatial") + theme(legend.position = "right")
```

